BlackCubes/covidmap-react-native

covid-mapper/App.js
covid-mapper/api/covidApi.js
covid-mapper/package-lock.json
covid-mapper/package.json
covid-mapper/store.js
covid-mapper/yarn.lock

1. Add `api` folder, `features` folder and `store.js`.
2. Install `react-redux`.
There needs to be a redux setup and an initial api call on the covid data.
Closes #4

Redux Toolkit Setup

---

covid-mapper/features/drawer/DrawerContent.js
covid-mapper/features/drawer/DrawerMenu.js
covid-mapper/package-lock.json
covid-mapper/package.json
covid-mapper/yarn.lock

1. Created `DrawerContent` component for Drawer layout and exported it to `DrawerMenu`.
2. Made placeholder Logo.
3. Styled DrawerContent with `styled-component/native`.
4. Pulled MenuBar from `origin/development`.
5. Installed `expo-linking` for opening project repo in mobile web browser.
Customize drawer navigation.
1. Create DrawerContent component with props parameter, import this component into DrawerMenu.
2. Provide `drawerContent` prop to `Drawer.Navigator` in `DrawerMenu.js`, like so: ` drawerContent={(props) => <DrawerContent {...props} />}`.
To open a URL in mobile browser from mobile app, install `expo-linking` and `import * as Linking from 'expo-linking` and add `Linking.openURL('https://github.com')` for example.
[Expo Linking docs](https://docs.expo.dev/guides/linking/) …

Finish Drawer Navigation setup.

---

covid-mapper/features/vaccine-layout/components/VaccineItem.js
covid-mapper/package-lock.json
covid-mapper/package.json
covid-mapper/yarn.lock

1. Installed `he` package to use `he.decode()` on `details` JSON string from API.
2.  Conditionally render text in `ViewMoreButton`.
HTML entities are present in JSON string. Need to parse those for readability.
Install package and use `.decode()` method with `details` as argument.
[he(HTML Entities) package used](https://www.npmjs.com/package/he)
Closes #31

Installed 'he' package to decode HTML entities 

---

covid-mapper/features/about/About.js
covid-mapper/features/about/component/AboutSection.js
covid-mapper/features/drawer/DrawerContent.js
covid-mapper/features/drawer/DrawerMenu.js
covid-mapper/features/drawer/components/Footer.js
covid-mapper/utils/teamData.js

1. Created array for team member data.
2. Made a basic layout for About Us.
Create About screen in drawer and basic layout for team intros later.
Javascript, FlatList, styled-components.
Closes #123

Create basic layout for About screen

---

covid-mapper/features/map-layout/MapLayout.js
covid-mapper/utils/index.js
covid-mapper/utils/retrieveCountyData.js

1. Transformed the user input and data to lower case in `retrieveCountyData` function to fix a bug.
2. Move the `retrieveCountyData` to its own file for better organization and cleaner code.
After the user enters a county, that data from the array should be fetched and rendered.
Closes #129

Fixed US Counties Bug

---

covid-mapper/features/searchbar/Searchbar.js

1. Add `.toLowerCase()` to transform user input to lowercase.
Queries has to be in lowercase for search State/County to work.
Use `.toLowerCase()`.
Closes #128

Change search input to lowercase in handleSearchSubmit

---

covid-mapper/features/map-layout/MapLayout.js
covid-mapper/features/searchbar/Searchbar.js

1. Import `Alert` from 'react-native' and prepare a function to render alert in Searchbar.
2. Created state variable in MapLayout to store alert message to be passed to Searchbar.
Create an alert that lists what user could search for.
Conditional rendering, hook, and Alert.
Closes #126

Prepare alert for invalid search input

---

covid-mapper/features/drawer/components/MainContent.js

1. Renamed labels.
Give drawer items better names based on if endpoint needs a query param.
Closes #146

Rename drawer item labels

---

covid-mapper/commons/components/Icons/index.js
covid-mapper/features/map-layout/USSearchMapLayout.js
covid-mapper/features/map-layout/USViewMapLayout.js
covid-mapper/features/map-layout/WorldSearchMapLayout.js
covid-mapper/features/map-layout/WorldViewMapLayout.js
covid-mapper/features/map-layout/components/popup-slider/PopupSlider.js
covid-mapper/features/map-layout/components/popup-slider/PopupSliderButton.js
covid-mapper/features/map-layout/components/popup-slider/index.js

1. Created and rendered a component that opens the Slider to create a better user experience.
When the user closes the Slider, there should be another button that they could open besides the searchbar icon.
The only way a user could open the slider is if the hit the searchbar icon, or if they hit the "enter" key on their keyboard. Yet, what if the user closes the Slider? Should they open it again by using the searchbar icon? Also, how would the user know to use the searchbar icon to open the Slider? The Slider Button component fixes these issues.
Closes #138

Slider Open Button

---

covid-mapper/features/map-layout/WorldSearchMapLayout.js
covid-mapper/features/map/Map.js

1. Set `mapRegion` as `userLocation` if permission to get user's location is denied.
2. Passed `userLocation` down to `Map`,
3. Added `useEffect` with `userLocation` as dependency to set a marker at user's current location.
4. Switched current location marker's color to red and searched location marker to green.
Refactor and set  `mapRegion` as initial region for marker if user doesn't allow app to get current location.
Hooks, conditionals, Array.map, objects.
Closes #148

Refactor markers and initial region

---

covid-mapper/features/drawer/DrawerMenu.js

1. Made background color darker for more contrast.
Make header component's background color darker to improving 
Hex code.
Closes #158

Drawer header background color change

---

covid-mapper/README.md

1. Added a README.md in project directory.
Add a README.
Closes #166

Add README - part 1

---

covid-mapper/features/vaccine-layout/VaccineLayout.js
covid-mapper/features/vaccine-layout/components/VaccineItem.js

1. Refactored `renderItem` function so that it takes in `{ item }` parameter and returns a `<VaccineItem {...props} />` instead of mapping over data(incorrectly implemented).
2. Moved `hideText` state from `VaccineItem` to `VaccineLayout` to fix bug.
Speed up the rendering of VaccineLayout FlatList.
Refactor`renderItem` and move `hideText` state to parent component(VaccineLayout), so that hide text functionality works properly.
Closes #177

Refactor vaccine components to speed up rendering

---

covid-mapper/app.json

1. Added `"softwareKeyboardLayoutMode": "pan"` to `app.json` inside "android" object 
Prevent keyboard from pushing elements up when user taps input field(on focus).
This app is made with "managed" workflow(not bare react native app), therefore it has no `androidManifest.xml`. To change keyboard layout mode, you have to modify `app.json`.
[Answer # 5](https://www.py4u.net/discuss/608543) has solutions for expo and bare react native apps.
Closes #182

Change keyboard layout mode to 'pan' 

---

covid-mapper/api/covidApi.js
covid-mapper/features/graphs/TimeLineGraph.js
covid-mapper/features/map-layout/components/popup-slider/PopupSliderArray.js
covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js
covid-mapper/features/map-layout/components/popup-slider/PopupSliderObject.js

1. Added conditional and ternaries in TimeLineGraph to prevent errors.
2. Adjusted covidApi to have `hasVaccine` for conditional render of graph labels.
3. Passed necessary data down to TimeLineGraph.
Null check, fix error from graph.
Conditional rendering, conditionals, booleans.
Closes #185

Adjust covidApi, conditional render, and null checks

---

covid-mapper/features/graphs/TimeLineGraph.js
covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js

1. Change tooltip styling.
2. Increase rotation angle for labels.
Improve graph styling.
Inline styling, styled-components.
Closes #189

Modify graph label rotation angle and styling

---

covid-mapper/api/covidApi.js
covid-mapper/features/graphs/OverviewGraph.js
covid-mapper/features/graphs/index.js
covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js

1. Created a new graph component called `OverviewGraph` that displays a progress chart for the API data that does not have a timeline sequence (or an array of data), but has constant data.
2. Fixed a tiny bug in `covidApi.js` where the `response` property was removed to the correct one to display the data.
For the data that does not have a timeline sequence (an array) but only single values, they should be represented as a pie graph.
Closes #191

Progress Graph Chart

---

covid-mapper/package.json

chore(package): version bump

---

covid-mapper/app.json
covid-mapper/eas.json
covid-mapper/package-lock.json
covid-mapper/yarn.lock

1. Generated `eas.json` from `eas build:configure` command
Publish app for QA testing.
Expo, EAS cli.

eas publish configuration

---

covid-mapper/app.json
covid-mapper/eas.json
covid-mapper/package-lock.json
covid-mapper/package.json
covid-mapper/yarn.lock

Code has already been reviewed.

dev to maiin

---

covid-mapper/app.json
covid-mapper/package.json

version bump to 0.1.1

---

covid-mapper/features/graphs/OverviewGraph.js
covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js

1. Changed the positioning of the overview graph and its subtitle for better UX.
2. Added space for better grammar for the slider data.
Ordering of textual data should be the same as represented by graph.
Closes #200

Fixed UX bug: Changed ordering of the graph data

---

covid-mapper/app.json
covid-mapper/package.json

Created new version bump
Closes #202

chore(version-bump): bump version

---

ACCEPTANCE.md

1. Created a file for the acceptance test for the QA team
To keep track of the file, and to save it for the QA team

Acceptance test file for QA team

---

covid-mapper/features/map-layout/USSearchMapLayout.js
covid-mapper/features/map-layout/USViewMapLayout.js
covid-mapper/features/map-layout/VaccineUSSearchMapLayout.js
covid-mapper/features/map-layout/VaccineUSViewMapLayout.js
covid-mapper/features/map-layout/VaccineWorldSearchMapLayout.js
covid-mapper/features/map-layout/VaccineWorldViewMapLayout.js
covid-mapper/features/map-layout/WorldSearchMapLayout.js
covid-mapper/features/map-layout/WorldViewMapLayout.js

1. Changed the initial regions of the map to render the US or World layout depending on the navigation route the user goes to.
When the user goes to the different drawer navigations, the map should correspond to the specific region selected from the route i.e. a Country navigation should display a map of the world. Currently, all of the navigation routes display California.
Closes #209

Changed the initial region of the map based on the navigation route

---

covid-mapper/features/graphs/TimeLineGraph.js
covid-mapper/features/map-layout/components/popup-slider/PopupSliderData.js

1. Bold some words in modal
Improve UX, readability
Styled-components, in-line styling.
Closes #211

Increase font weight for data

---

covid-mapper/app.json
covid-mapper/features/about/About.js
covid-mapper/features/drawer/components/Footer.js
covid-mapper/package.json

1. Updated the version numbers in `app.json` and `package.json`.
2. Added a version number at the bottoms of both the Sidebar and in the "About Us" page so that the users could know what version the app is running on.
There should be an app version number at the bottom of the Sidebar, or in the "About Us" page.
Closes #217

Added Version Number at bottom of Sidebar/About Us page
